### ISSUE TITLE
Override __contains__ in Wrapper to get more intuitive behavior

### ISSUE THREAD

**Issue by jbemmel** [nokia/pysros#4]
At https://github.com/nokia/pysros/blob/main/pysros/wrappers.py#L74 some Python operators are overridden, but not all

For example:
```
cards = c.running.get("/nokia-state:state/card")
mdaType = cards[1]['mda'][1]['equipped-type'] # "s36-100gb-qsfp28"
print( 'qsfp' in mdaType ) # False(!)
```

mdaType is of type 'Leaf', it looks like a string when printed but it does not behave like a string

**Comment by jgcumming** [comment]
Cannot be replicated:

```
>>> print( 'qsfp' in mdaType )
True
>>> print( 'qsfp' in mdaType.data )
True
```
